// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: modules/game/core/entity/character_box.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CharacterBoxValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeaponType    string                 `protobuf:"bytes,1,opt,name=weapon_type,json=weaponType,proto3" json:"weapon_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterBoxValue) Reset() {
	*x = CharacterBoxValue{}
	mi := &file_modules_game_core_entity_character_box_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterBoxValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterBoxValue) ProtoMessage() {}

func (x *CharacterBoxValue) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_entity_character_box_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterBoxValue.ProtoReflect.Descriptor instead.
func (*CharacterBoxValue) Descriptor() ([]byte, []int) {
	return file_modules_game_core_entity_character_box_proto_rawDescGZIP(), []int{0}
}

func (x *CharacterBoxValue) GetWeaponType() string {
	if x != nil {
		return x.WeaponType
	}
	return ""
}

var File_modules_game_core_entity_character_box_proto protoreflect.FileDescriptor

const file_modules_game_core_entity_character_box_proto_rawDesc = "" +
	"\n" +
	",modules/game/core/entity/character_box.proto\x12\x10game.core.entity\"4\n" +
	"\x11CharacterBoxValue\x12\x1f\n" +
	"\vweapon_type\x18\x01 \x01(\tR\n" +
	"weaponTypeB3Z1squad-survival-be/modules/game/core/entity;entityb\x06proto3"

var (
	file_modules_game_core_entity_character_box_proto_rawDescOnce sync.Once
	file_modules_game_core_entity_character_box_proto_rawDescData []byte
)

func file_modules_game_core_entity_character_box_proto_rawDescGZIP() []byte {
	file_modules_game_core_entity_character_box_proto_rawDescOnce.Do(func() {
		file_modules_game_core_entity_character_box_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_game_core_entity_character_box_proto_rawDesc), len(file_modules_game_core_entity_character_box_proto_rawDesc)))
	})
	return file_modules_game_core_entity_character_box_proto_rawDescData
}

var file_modules_game_core_entity_character_box_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_modules_game_core_entity_character_box_proto_goTypes = []any{
	(*CharacterBoxValue)(nil), // 0: game.core.entity.CharacterBoxValue
}
var file_modules_game_core_entity_character_box_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_modules_game_core_entity_character_box_proto_init() }
func file_modules_game_core_entity_character_box_proto_init() {
	if File_modules_game_core_entity_character_box_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_game_core_entity_character_box_proto_rawDesc), len(file_modules_game_core_entity_character_box_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modules_game_core_entity_character_box_proto_goTypes,
		DependencyIndexes: file_modules_game_core_entity_character_box_proto_depIdxs,
		MessageInfos:      file_modules_game_core_entity_character_box_proto_msgTypes,
	}.Build()
	File_modules_game_core_entity_character_box_proto = out.File
	file_modules_game_core_entity_character_box_proto_goTypes = nil
	file_modules_game_core_entity_character_box_proto_depIdxs = nil
}
