// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: modules/game/core/entity/experience_package.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExperiencePackageTier int32

const (
	ExperiencePackageTier_EXPERIENCE_PACKAGE_TIER_UNSPECIFIED ExperiencePackageTier = 0
	ExperiencePackageTier_EXPERIENCE_PACKAGE_TIER_SMALL       ExperiencePackageTier = 1
	ExperiencePackageTier_EXPERIENCE_PACKAGE_TIER_MEDIUM      ExperiencePackageTier = 2
	ExperiencePackageTier_EXPERIENCE_PACKAGE_TIER_LARGE       ExperiencePackageTier = 3
)

// Enum value maps for ExperiencePackageTier.
var (
	ExperiencePackageTier_name = map[int32]string{
		0: "EXPERIENCE_PACKAGE_TIER_UNSPECIFIED",
		1: "EXPERIENCE_PACKAGE_TIER_SMALL",
		2: "EXPERIENCE_PACKAGE_TIER_MEDIUM",
		3: "EXPERIENCE_PACKAGE_TIER_LARGE",
	}
	ExperiencePackageTier_value = map[string]int32{
		"EXPERIENCE_PACKAGE_TIER_UNSPECIFIED": 0,
		"EXPERIENCE_PACKAGE_TIER_SMALL":       1,
		"EXPERIENCE_PACKAGE_TIER_MEDIUM":      2,
		"EXPERIENCE_PACKAGE_TIER_LARGE":       3,
	}
)

func (x ExperiencePackageTier) Enum() *ExperiencePackageTier {
	p := new(ExperiencePackageTier)
	*p = x
	return p
}

func (x ExperiencePackageTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExperiencePackageTier) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_game_core_entity_experience_package_proto_enumTypes[0].Descriptor()
}

func (ExperiencePackageTier) Type() protoreflect.EnumType {
	return &file_modules_game_core_entity_experience_package_proto_enumTypes[0]
}

func (x ExperiencePackageTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExperiencePackageTier.Descriptor instead.
func (ExperiencePackageTier) EnumDescriptor() ([]byte, []int) {
	return file_modules_game_core_entity_experience_package_proto_rawDescGZIP(), []int{0}
}

type ExperiencePackageValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tier          ExperiencePackageTier  `protobuf:"varint,1,opt,name=tier,proto3,enum=game.core.entity.ExperiencePackageTier" json:"tier,omitempty"`
	Experience    uint64                 `protobuf:"varint,2,opt,name=experience,proto3" json:"experience,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperiencePackageValue) Reset() {
	*x = ExperiencePackageValue{}
	mi := &file_modules_game_core_entity_experience_package_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperiencePackageValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperiencePackageValue) ProtoMessage() {}

func (x *ExperiencePackageValue) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_entity_experience_package_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperiencePackageValue.ProtoReflect.Descriptor instead.
func (*ExperiencePackageValue) Descriptor() ([]byte, []int) {
	return file_modules_game_core_entity_experience_package_proto_rawDescGZIP(), []int{0}
}

func (x *ExperiencePackageValue) GetTier() ExperiencePackageTier {
	if x != nil {
		return x.Tier
	}
	return ExperiencePackageTier_EXPERIENCE_PACKAGE_TIER_UNSPECIFIED
}

func (x *ExperiencePackageValue) GetExperience() uint64 {
	if x != nil {
		return x.Experience
	}
	return 0
}

var File_modules_game_core_entity_experience_package_proto protoreflect.FileDescriptor

const file_modules_game_core_entity_experience_package_proto_rawDesc = "" +
	"\n" +
	"1modules/game/core/entity/experience_package.proto\x12\x10game.core.entity\"u\n" +
	"\x16ExperiencePackageValue\x12;\n" +
	"\x04tier\x18\x01 \x01(\x0e2'.game.core.entity.ExperiencePackageTierR\x04tier\x12\x1e\n" +
	"\n" +
	"experience\x18\x02 \x01(\x04R\n" +
	"experience*\xaa\x01\n" +
	"\x15ExperiencePackageTier\x12'\n" +
	"#EXPERIENCE_PACKAGE_TIER_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dEXPERIENCE_PACKAGE_TIER_SMALL\x10\x01\x12\"\n" +
	"\x1eEXPERIENCE_PACKAGE_TIER_MEDIUM\x10\x02\x12!\n" +
	"\x1dEXPERIENCE_PACKAGE_TIER_LARGE\x10\x03B3Z1squad-survival-be/modules/game/core/entity;entityb\x06proto3"

var (
	file_modules_game_core_entity_experience_package_proto_rawDescOnce sync.Once
	file_modules_game_core_entity_experience_package_proto_rawDescData []byte
)

func file_modules_game_core_entity_experience_package_proto_rawDescGZIP() []byte {
	file_modules_game_core_entity_experience_package_proto_rawDescOnce.Do(func() {
		file_modules_game_core_entity_experience_package_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_game_core_entity_experience_package_proto_rawDesc), len(file_modules_game_core_entity_experience_package_proto_rawDesc)))
	})
	return file_modules_game_core_entity_experience_package_proto_rawDescData
}

var file_modules_game_core_entity_experience_package_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_modules_game_core_entity_experience_package_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_modules_game_core_entity_experience_package_proto_goTypes = []any{
	(ExperiencePackageTier)(0),     // 0: game.core.entity.ExperiencePackageTier
	(*ExperiencePackageValue)(nil), // 1: game.core.entity.ExperiencePackageValue
}
var file_modules_game_core_entity_experience_package_proto_depIdxs = []int32{
	0, // 0: game.core.entity.ExperiencePackageValue.tier:type_name -> game.core.entity.ExperiencePackageTier
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_modules_game_core_entity_experience_package_proto_init() }
func file_modules_game_core_entity_experience_package_proto_init() {
	if File_modules_game_core_entity_experience_package_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_game_core_entity_experience_package_proto_rawDesc), len(file_modules_game_core_entity_experience_package_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modules_game_core_entity_experience_package_proto_goTypes,
		DependencyIndexes: file_modules_game_core_entity_experience_package_proto_depIdxs,
		EnumInfos:         file_modules_game_core_entity_experience_package_proto_enumTypes,
		MessageInfos:      file_modules_game_core_entity_experience_package_proto_msgTypes,
	}.Build()
	File_modules_game_core_entity_experience_package_proto = out.File
	file_modules_game_core_entity_experience_package_proto_goTypes = nil
	file_modules_game_core_entity_experience_package_proto_depIdxs = nil
}
