// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: modules/game/core/system/character_box_state.proto

package system

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	entity "squad-survival-be/modules/game/core/entity"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CharacterBoxEventType int32

const (
	CharacterBoxEventType_CHARACTER_BOX_EVENT_TYPE_UNSPECIFIED CharacterBoxEventType = 0
	CharacterBoxEventType_CHARACTER_BOX_EVENT_TYPE_SPAWNED     CharacterBoxEventType = 1
	CharacterBoxEventType_CHARACTER_BOX_EVENT_TYPE_DESPAWNED   CharacterBoxEventType = 2
)

// Enum value maps for CharacterBoxEventType.
var (
	CharacterBoxEventType_name = map[int32]string{
		0: "CHARACTER_BOX_EVENT_TYPE_UNSPECIFIED",
		1: "CHARACTER_BOX_EVENT_TYPE_SPAWNED",
		2: "CHARACTER_BOX_EVENT_TYPE_DESPAWNED",
	}
	CharacterBoxEventType_value = map[string]int32{
		"CHARACTER_BOX_EVENT_TYPE_UNSPECIFIED": 0,
		"CHARACTER_BOX_EVENT_TYPE_SPAWNED":     1,
		"CHARACTER_BOX_EVENT_TYPE_DESPAWNED":   2,
	}
)

func (x CharacterBoxEventType) Enum() *CharacterBoxEventType {
	p := new(CharacterBoxEventType)
	*p = x
	return p
}

func (x CharacterBoxEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CharacterBoxEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_game_core_system_character_box_state_proto_enumTypes[0].Descriptor()
}

func (CharacterBoxEventType) Type() protoreflect.EnumType {
	return &file_modules_game_core_system_character_box_state_proto_enumTypes[0]
}

func (x CharacterBoxEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CharacterBoxEventType.Descriptor instead.
func (CharacterBoxEventType) EnumDescriptor() ([]byte, []int) {
	return file_modules_game_core_system_character_box_state_proto_rawDescGZIP(), []int{0}
}

type CharacterBoxStateBatch struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Tick          int64                     `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Events        []*CharacterBoxStateEvent `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterBoxStateBatch) Reset() {
	*x = CharacterBoxStateBatch{}
	mi := &file_modules_game_core_system_character_box_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterBoxStateBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterBoxStateBatch) ProtoMessage() {}

func (x *CharacterBoxStateBatch) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_system_character_box_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterBoxStateBatch.ProtoReflect.Descriptor instead.
func (*CharacterBoxStateBatch) Descriptor() ([]byte, []int) {
	return file_modules_game_core_system_character_box_state_proto_rawDescGZIP(), []int{0}
}

func (x *CharacterBoxStateBatch) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *CharacterBoxStateBatch) GetEvents() []*CharacterBoxStateEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type CharacterBoxStateEvent struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	EventType     CharacterBoxEventType     `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=game.core.system.CharacterBoxEventType" json:"event_type,omitempty"`
	BoxId         string                    `protobuf:"bytes,2,opt,name=box_id,json=boxId,proto3" json:"box_id,omitempty"`
	Position      *Vector2                  `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Value         *entity.CharacterBoxValue `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterBoxStateEvent) Reset() {
	*x = CharacterBoxStateEvent{}
	mi := &file_modules_game_core_system_character_box_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterBoxStateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterBoxStateEvent) ProtoMessage() {}

func (x *CharacterBoxStateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_system_character_box_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterBoxStateEvent.ProtoReflect.Descriptor instead.
func (*CharacterBoxStateEvent) Descriptor() ([]byte, []int) {
	return file_modules_game_core_system_character_box_state_proto_rawDescGZIP(), []int{1}
}

func (x *CharacterBoxStateEvent) GetEventType() CharacterBoxEventType {
	if x != nil {
		return x.EventType
	}
	return CharacterBoxEventType_CHARACTER_BOX_EVENT_TYPE_UNSPECIFIED
}

func (x *CharacterBoxStateEvent) GetBoxId() string {
	if x != nil {
		return x.BoxId
	}
	return ""
}

func (x *CharacterBoxStateEvent) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *CharacterBoxStateEvent) GetValue() *entity.CharacterBoxValue {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_modules_game_core_system_character_box_state_proto protoreflect.FileDescriptor

const file_modules_game_core_system_character_box_state_proto_rawDesc = "" +
	"\n" +
	"2modules/game/core/system/character_box_state.proto\x12\x10game.core.system\x1a,modules/game/core/entity/character_box.proto\x1a%modules/game/core/system/vector.proto\"n\n" +
	"\x16CharacterBoxStateBatch\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x03R\x04tick\x12@\n" +
	"\x06events\x18\x02 \x03(\v2(.game.core.system.CharacterBoxStateEventR\x06events\"\xe9\x01\n" +
	"\x16CharacterBoxStateEvent\x12F\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2'.game.core.system.CharacterBoxEventTypeR\teventType\x12\x15\n" +
	"\x06box_id\x18\x02 \x01(\tR\x05boxId\x125\n" +
	"\bposition\x18\x03 \x01(\v2\x19.game.core.system.Vector2R\bposition\x129\n" +
	"\x05value\x18\x04 \x01(\v2#.game.core.entity.CharacterBoxValueR\x05value*\x8f\x01\n" +
	"\x15CharacterBoxEventType\x12(\n" +
	"$CHARACTER_BOX_EVENT_TYPE_UNSPECIFIED\x10\x00\x12$\n" +
	" CHARACTER_BOX_EVENT_TYPE_SPAWNED\x10\x01\x12&\n" +
	"\"CHARACTER_BOX_EVENT_TYPE_DESPAWNED\x10\x02B3Z1squad-survival-be/modules/game/core/system;systemb\x06proto3"

var (
	file_modules_game_core_system_character_box_state_proto_rawDescOnce sync.Once
	file_modules_game_core_system_character_box_state_proto_rawDescData []byte
)

func file_modules_game_core_system_character_box_state_proto_rawDescGZIP() []byte {
	file_modules_game_core_system_character_box_state_proto_rawDescOnce.Do(func() {
		file_modules_game_core_system_character_box_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_game_core_system_character_box_state_proto_rawDesc), len(file_modules_game_core_system_character_box_state_proto_rawDesc)))
	})
	return file_modules_game_core_system_character_box_state_proto_rawDescData
}

var file_modules_game_core_system_character_box_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_modules_game_core_system_character_box_state_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_modules_game_core_system_character_box_state_proto_goTypes = []any{
	(CharacterBoxEventType)(0),       // 0: game.core.system.CharacterBoxEventType
	(*CharacterBoxStateBatch)(nil),   // 1: game.core.system.CharacterBoxStateBatch
	(*CharacterBoxStateEvent)(nil),   // 2: game.core.system.CharacterBoxStateEvent
	(*Vector2)(nil),                  // 3: game.core.system.Vector2
	(*entity.CharacterBoxValue)(nil), // 4: game.core.entity.CharacterBoxValue
}
var file_modules_game_core_system_character_box_state_proto_depIdxs = []int32{
	2, // 0: game.core.system.CharacterBoxStateBatch.events:type_name -> game.core.system.CharacterBoxStateEvent
	0, // 1: game.core.system.CharacterBoxStateEvent.event_type:type_name -> game.core.system.CharacterBoxEventType
	3, // 2: game.core.system.CharacterBoxStateEvent.position:type_name -> game.core.system.Vector2
	4, // 3: game.core.system.CharacterBoxStateEvent.value:type_name -> game.core.entity.CharacterBoxValue
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_modules_game_core_system_character_box_state_proto_init() }
func file_modules_game_core_system_character_box_state_proto_init() {
	if File_modules_game_core_system_character_box_state_proto != nil {
		return
	}
	file_modules_game_core_system_vector_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_game_core_system_character_box_state_proto_rawDesc), len(file_modules_game_core_system_character_box_state_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modules_game_core_system_character_box_state_proto_goTypes,
		DependencyIndexes: file_modules_game_core_system_character_box_state_proto_depIdxs,
		EnumInfos:         file_modules_game_core_system_character_box_state_proto_enumTypes,
		MessageInfos:      file_modules_game_core_system_character_box_state_proto_msgTypes,
	}.Build()
	File_modules_game_core_system_character_box_state_proto = out.File
	file_modules_game_core_system_character_box_state_proto_goTypes = nil
	file_modules_game_core_system_character_box_state_proto_depIdxs = nil
}
