syntax = "proto3";

package game.core.system;

option go_package = "squad-survival-be/modules/game/core/system;system";

import "modules/game/core/system/vector.proto";

message CombatEventBatch {
  int64 tick = 1;
  repeated CombatEvent events = 2;
}

message CombatEvent {
  oneof event {
    AttackStarted attack_started = 1;
    DamageApplied damage_applied = 2;
    CharacterDied character_died = 3;
    ProjectileSpawned projectile_spawned = 4;
    ProjectileHit projectile_hit = 5;
    ProjectileExpired projectile_expired = 6;
    SkillStarted skill_started = 7;
  }
}

message SkillStarted {
  string action_id = 1;
  string skill_id = 2;
  string attacker_user_id = 3;
  string attacker_character_id = 4;
  string target_user_id = 5;
  string target_character_id = 6;
  string weapon_id = 7;
  Vector2 direction = 8;
  int64 start_tick = 9;
  int64 impact_tick = 10;
  int64 complete_tick = 11;
  repeated string tags = 12;
}

message AttackStarted {
  string action_id = 1;
  string attacker_user_id = 2;
  string attacker_character_id = 3;
  string target_user_id = 4;
  string target_character_id = 5;
  string weapon_type = 6;
  int64 start_tick = 7;
  int64 impact_tick = 8;
  int64 complete_tick = 9;
  string weapon_id = 10;
  int32 attack_count = 11;
  repeated string tags = 12;
}

message DamageApplied {
  string action_id = 1;
  string attacker_user_id = 2;
  string attacker_character_id = 3;
  string target_user_id = 4;
  string target_character_id = 5;
  double damage = 6;
  double remaining_health = 7;
  int64 tick = 8;
  string projectile_id = 9;
  bool critical = 10;
  string hit_id = 11;
  repeated string tags = 12;
}

message CharacterDied {
  string action_id = 1;
  string killer_user_id = 2;
  string killer_character_id = 3;
  string target_user_id = 4;
  string target_character_id = 5;
  int64 tick = 6;
  string projectile_id = 7;
  string hit_id = 8;
  repeated string tags = 9;
}

message ProjectileSpawned {
  string projectile_id = 1;
  string action_id = 2;
  string attacker_user_id = 3;
  string attacker_character_id = 4;
  string target_user_id = 5;
  string target_character_id = 6;
  string weapon_type = 7;
  string weapon_id = 8;
  Vector2 position = 9;
  Vector2 direction = 10;
  double speed = 11;
  int64 tick = 12;
  string hit_id = 13;
  repeated string tags = 14;
}

message ProjectileHit {
  string projectile_id = 1;
  string action_id = 2;
  string attacker_user_id = 3;
  string attacker_character_id = 4;
  string target_user_id = 5;
  string target_character_id = 6;
  Vector2 position = 7;
  int64 tick = 8;
  string hit_id = 9;
  repeated string tags = 10;
}

message ProjectileExpired {
  string projectile_id = 1;
  string action_id = 2;
  string attacker_user_id = 3;
  string attacker_character_id = 4;
  string target_user_id = 5;
  string target_character_id = 6;
  Vector2 position = 7;
  int64 tick = 8;
  string hit_id = 9;
  repeated string tags = 10;
}
