// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: modules/game/core/system/experience_package_state.proto

package system

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	entity "squad-survival-be/modules/game/core/entity"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExperiencePackageEventType int32

const (
	ExperiencePackageEventType_EXPERIENCE_PACKAGE_EVENT_TYPE_UNSPECIFIED ExperiencePackageEventType = 0
	ExperiencePackageEventType_EXPERIENCE_PACKAGE_EVENT_TYPE_DETECTED    ExperiencePackageEventType = 1
	ExperiencePackageEventType_EXPERIENCE_PACKAGE_EVENT_TYPE_LOST        ExperiencePackageEventType = 2
	ExperiencePackageEventType_EXPERIENCE_PACKAGE_EVENT_TYPE_COLLECTED   ExperiencePackageEventType = 3
)

// Enum value maps for ExperiencePackageEventType.
var (
	ExperiencePackageEventType_name = map[int32]string{
		0: "EXPERIENCE_PACKAGE_EVENT_TYPE_UNSPECIFIED",
		1: "EXPERIENCE_PACKAGE_EVENT_TYPE_DETECTED",
		2: "EXPERIENCE_PACKAGE_EVENT_TYPE_LOST",
		3: "EXPERIENCE_PACKAGE_EVENT_TYPE_COLLECTED",
	}
	ExperiencePackageEventType_value = map[string]int32{
		"EXPERIENCE_PACKAGE_EVENT_TYPE_UNSPECIFIED": 0,
		"EXPERIENCE_PACKAGE_EVENT_TYPE_DETECTED":    1,
		"EXPERIENCE_PACKAGE_EVENT_TYPE_LOST":        2,
		"EXPERIENCE_PACKAGE_EVENT_TYPE_COLLECTED":   3,
	}
)

func (x ExperiencePackageEventType) Enum() *ExperiencePackageEventType {
	p := new(ExperiencePackageEventType)
	*p = x
	return p
}

func (x ExperiencePackageEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExperiencePackageEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_game_core_system_experience_package_state_proto_enumTypes[0].Descriptor()
}

func (ExperiencePackageEventType) Type() protoreflect.EnumType {
	return &file_modules_game_core_system_experience_package_state_proto_enumTypes[0]
}

func (x ExperiencePackageEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExperiencePackageEventType.Descriptor instead.
func (ExperiencePackageEventType) EnumDescriptor() ([]byte, []int) {
	return file_modules_game_core_system_experience_package_state_proto_rawDescGZIP(), []int{0}
}

type ExperiencePackageStateBatch struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Tick          int64                          `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Events        []*ExperiencePackageStateEvent `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperiencePackageStateBatch) Reset() {
	*x = ExperiencePackageStateBatch{}
	mi := &file_modules_game_core_system_experience_package_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperiencePackageStateBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperiencePackageStateBatch) ProtoMessage() {}

func (x *ExperiencePackageStateBatch) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_system_experience_package_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperiencePackageStateBatch.ProtoReflect.Descriptor instead.
func (*ExperiencePackageStateBatch) Descriptor() ([]byte, []int) {
	return file_modules_game_core_system_experience_package_state_proto_rawDescGZIP(), []int{0}
}

func (x *ExperiencePackageStateBatch) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *ExperiencePackageStateBatch) GetEvents() []*ExperiencePackageStateEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ExperiencePackageStateEvent struct {
	state              protoimpl.MessageState         `protogen:"open.v1"`
	EventType          ExperiencePackageEventType     `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=game.core.system.ExperiencePackageEventType" json:"event_type,omitempty"`
	PackageId          string                         `protobuf:"bytes,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Position           *Vector2                       `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Value              *entity.ExperiencePackageValue `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	CollectorUserId    string                         `protobuf:"bytes,5,opt,name=collector_user_id,json=collectorUserId,proto3" json:"collector_user_id,omitempty"`
	CollectorSessionId string                         `protobuf:"bytes,6,opt,name=collector_session_id,json=collectorSessionId,proto3" json:"collector_session_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExperiencePackageStateEvent) Reset() {
	*x = ExperiencePackageStateEvent{}
	mi := &file_modules_game_core_system_experience_package_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperiencePackageStateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperiencePackageStateEvent) ProtoMessage() {}

func (x *ExperiencePackageStateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_system_experience_package_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperiencePackageStateEvent.ProtoReflect.Descriptor instead.
func (*ExperiencePackageStateEvent) Descriptor() ([]byte, []int) {
	return file_modules_game_core_system_experience_package_state_proto_rawDescGZIP(), []int{1}
}

func (x *ExperiencePackageStateEvent) GetEventType() ExperiencePackageEventType {
	if x != nil {
		return x.EventType
	}
	return ExperiencePackageEventType_EXPERIENCE_PACKAGE_EVENT_TYPE_UNSPECIFIED
}

func (x *ExperiencePackageStateEvent) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *ExperiencePackageStateEvent) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *ExperiencePackageStateEvent) GetValue() *entity.ExperiencePackageValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ExperiencePackageStateEvent) GetCollectorUserId() string {
	if x != nil {
		return x.CollectorUserId
	}
	return ""
}

func (x *ExperiencePackageStateEvent) GetCollectorSessionId() string {
	if x != nil {
		return x.CollectorSessionId
	}
	return ""
}

var File_modules_game_core_system_experience_package_state_proto protoreflect.FileDescriptor

const file_modules_game_core_system_experience_package_state_proto_rawDesc = "" +
	"\n" +
	"7modules/game/core/system/experience_package_state.proto\x12\x10game.core.system\x1a1modules/game/core/entity/experience_package.proto\x1a%modules/game/core/system/vector.proto\"x\n" +
	"\x1bExperiencePackageStateBatch\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x03R\x04tick\x12E\n" +
	"\x06events\x18\x02 \x03(\v2-.game.core.system.ExperiencePackageStateEventR\x06events\"\xde\x02\n" +
	"\x1bExperiencePackageStateEvent\x12K\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2,.game.core.system.ExperiencePackageEventTypeR\teventType\x12\x1d\n" +
	"\n" +
	"package_id\x18\x02 \x01(\tR\tpackageId\x125\n" +
	"\bposition\x18\x03 \x01(\v2\x19.game.core.system.Vector2R\bposition\x12>\n" +
	"\x05value\x18\x04 \x01(\v2(.game.core.entity.ExperiencePackageValueR\x05value\x12*\n" +
	"\x11collector_user_id\x18\x05 \x01(\tR\x0fcollectorUserId\x120\n" +
	"\x14collector_session_id\x18\x06 \x01(\tR\x12collectorSessionId*\xcc\x01\n" +
	"\x1aExperiencePackageEventType\x12-\n" +
	")EXPERIENCE_PACKAGE_EVENT_TYPE_UNSPECIFIED\x10\x00\x12*\n" +
	"&EXPERIENCE_PACKAGE_EVENT_TYPE_DETECTED\x10\x01\x12&\n" +
	"\"EXPERIENCE_PACKAGE_EVENT_TYPE_LOST\x10\x02\x12+\n" +
	"'EXPERIENCE_PACKAGE_EVENT_TYPE_COLLECTED\x10\x03B3Z1squad-survival-be/modules/game/core/system;systemb\x06proto3"

var (
	file_modules_game_core_system_experience_package_state_proto_rawDescOnce sync.Once
	file_modules_game_core_system_experience_package_state_proto_rawDescData []byte
)

func file_modules_game_core_system_experience_package_state_proto_rawDescGZIP() []byte {
	file_modules_game_core_system_experience_package_state_proto_rawDescOnce.Do(func() {
		file_modules_game_core_system_experience_package_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_game_core_system_experience_package_state_proto_rawDesc), len(file_modules_game_core_system_experience_package_state_proto_rawDesc)))
	})
	return file_modules_game_core_system_experience_package_state_proto_rawDescData
}

var file_modules_game_core_system_experience_package_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_modules_game_core_system_experience_package_state_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_modules_game_core_system_experience_package_state_proto_goTypes = []any{
	(ExperiencePackageEventType)(0),       // 0: game.core.system.ExperiencePackageEventType
	(*ExperiencePackageStateBatch)(nil),   // 1: game.core.system.ExperiencePackageStateBatch
	(*ExperiencePackageStateEvent)(nil),   // 2: game.core.system.ExperiencePackageStateEvent
	(*Vector2)(nil),                       // 3: game.core.system.Vector2
	(*entity.ExperiencePackageValue)(nil), // 4: game.core.entity.ExperiencePackageValue
}
var file_modules_game_core_system_experience_package_state_proto_depIdxs = []int32{
	2, // 0: game.core.system.ExperiencePackageStateBatch.events:type_name -> game.core.system.ExperiencePackageStateEvent
	0, // 1: game.core.system.ExperiencePackageStateEvent.event_type:type_name -> game.core.system.ExperiencePackageEventType
	3, // 2: game.core.system.ExperiencePackageStateEvent.position:type_name -> game.core.system.Vector2
	4, // 3: game.core.system.ExperiencePackageStateEvent.value:type_name -> game.core.entity.ExperiencePackageValue
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_modules_game_core_system_experience_package_state_proto_init() }
func file_modules_game_core_system_experience_package_state_proto_init() {
	if File_modules_game_core_system_experience_package_state_proto != nil {
		return
	}
	file_modules_game_core_system_vector_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_game_core_system_experience_package_state_proto_rawDesc), len(file_modules_game_core_system_experience_package_state_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modules_game_core_system_experience_package_state_proto_goTypes,
		DependencyIndexes: file_modules_game_core_system_experience_package_state_proto_depIdxs,
		EnumInfos:         file_modules_game_core_system_experience_package_state_proto_enumTypes,
		MessageInfos:      file_modules_game_core_system_experience_package_state_proto_msgTypes,
	}.Build()
	File_modules_game_core_system_experience_package_state_proto = out.File
	file_modules_game_core_system_experience_package_state_proto_goTypes = nil
	file_modules_game_core_system_experience_package_state_proto_depIdxs = nil
}
