// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: modules/game/core/system/player_movement.proto

package system

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerMovementSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          int64                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Players       []*PlayerMovement      `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Self          *PlayerMovement        `protobuf:"bytes,3,opt,name=self,proto3" json:"self,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerMovementSnapshot) Reset() {
	*x = PlayerMovementSnapshot{}
	mi := &file_modules_game_core_system_player_movement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMovementSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMovementSnapshot) ProtoMessage() {}

func (x *PlayerMovementSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_system_player_movement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMovementSnapshot.ProtoReflect.Descriptor instead.
func (*PlayerMovementSnapshot) Descriptor() ([]byte, []int) {
	return file_modules_game_core_system_player_movement_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerMovementSnapshot) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *PlayerMovementSnapshot) GetPlayers() []*PlayerMovement {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *PlayerMovementSnapshot) GetSelf() *PlayerMovement {
	if x != nil {
		return x.Self
	}
	return nil
}

type PlayerMovement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Position      *Vector2               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Facing        *Vector2               `protobuf:"bytes,3,opt,name=facing,proto3" json:"facing,omitempty"`
	Direction     *Vector2               `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	Characters    []*CharacterMovement   `protobuf:"bytes,5,rep,name=characters,proto3" json:"characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerMovement) Reset() {
	*x = PlayerMovement{}
	mi := &file_modules_game_core_system_player_movement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMovement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMovement) ProtoMessage() {}

func (x *PlayerMovement) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_system_player_movement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMovement.ProtoReflect.Descriptor instead.
func (*PlayerMovement) Descriptor() ([]byte, []int) {
	return file_modules_game_core_system_player_movement_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerMovement) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PlayerMovement) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlayerMovement) GetFacing() *Vector2 {
	if x != nil {
		return x.Facing
	}
	return nil
}

func (x *PlayerMovement) GetDirection() *Vector2 {
	if x != nil {
		return x.Direction
	}
	return nil
}

func (x *PlayerMovement) GetCharacters() []*CharacterMovement {
	if x != nil {
		return x.Characters
	}
	return nil
}

type CharacterMovement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Position      *Vector2               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterMovement) Reset() {
	*x = CharacterMovement{}
	mi := &file_modules_game_core_system_player_movement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterMovement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterMovement) ProtoMessage() {}

func (x *CharacterMovement) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_system_player_movement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterMovement.ProtoReflect.Descriptor instead.
func (*CharacterMovement) Descriptor() ([]byte, []int) {
	return file_modules_game_core_system_player_movement_proto_rawDescGZIP(), []int{2}
}

func (x *CharacterMovement) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *CharacterMovement) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

var File_modules_game_core_system_player_movement_proto protoreflect.FileDescriptor

const file_modules_game_core_system_player_movement_proto_rawDesc = "" +
	"\n" +
	".modules/game/core/system/player_movement.proto\x12\x10game.core.system\x1a%modules/game/core/system/vector.proto\"\x9e\x01\n" +
	"\x16PlayerMovementSnapshot\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x03R\x04tick\x12:\n" +
	"\aplayers\x18\x02 \x03(\v2 .game.core.system.PlayerMovementR\aplayers\x124\n" +
	"\x04self\x18\x03 \x01(\v2 .game.core.system.PlayerMovementR\x04self\"\x97\x02\n" +
	"\x0ePlayerMovement\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x125\n" +
	"\bposition\x18\x02 \x01(\v2\x19.game.core.system.Vector2R\bposition\x121\n" +
	"\x06facing\x18\x03 \x01(\v2\x19.game.core.system.Vector2R\x06facing\x127\n" +
	"\tdirection\x18\x04 \x01(\v2\x19.game.core.system.Vector2R\tdirection\x12C\n" +
	"\n" +
	"characters\x18\x05 \x03(\v2#.game.core.system.CharacterMovementR\n" +
	"characters\"m\n" +
	"\x11CharacterMovement\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x125\n" +
	"\bposition\x18\x02 \x01(\v2\x19.game.core.system.Vector2R\bpositionB3Z1squad-survival-be/modules/game/core/system;systemb\x06proto3"

var (
	file_modules_game_core_system_player_movement_proto_rawDescOnce sync.Once
	file_modules_game_core_system_player_movement_proto_rawDescData []byte
)

func file_modules_game_core_system_player_movement_proto_rawDescGZIP() []byte {
	file_modules_game_core_system_player_movement_proto_rawDescOnce.Do(func() {
		file_modules_game_core_system_player_movement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_game_core_system_player_movement_proto_rawDesc), len(file_modules_game_core_system_player_movement_proto_rawDesc)))
	})
	return file_modules_game_core_system_player_movement_proto_rawDescData
}

var file_modules_game_core_system_player_movement_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_modules_game_core_system_player_movement_proto_goTypes = []any{
	(*PlayerMovementSnapshot)(nil), // 0: game.core.system.PlayerMovementSnapshot
	(*PlayerMovement)(nil),         // 1: game.core.system.PlayerMovement
	(*CharacterMovement)(nil),      // 2: game.core.system.CharacterMovement
	(*Vector2)(nil),                // 3: game.core.system.Vector2
}
var file_modules_game_core_system_player_movement_proto_depIdxs = []int32{
	1, // 0: game.core.system.PlayerMovementSnapshot.players:type_name -> game.core.system.PlayerMovement
	1, // 1: game.core.system.PlayerMovementSnapshot.self:type_name -> game.core.system.PlayerMovement
	3, // 2: game.core.system.PlayerMovement.position:type_name -> game.core.system.Vector2
	3, // 3: game.core.system.PlayerMovement.facing:type_name -> game.core.system.Vector2
	3, // 4: game.core.system.PlayerMovement.direction:type_name -> game.core.system.Vector2
	2, // 5: game.core.system.PlayerMovement.characters:type_name -> game.core.system.CharacterMovement
	3, // 6: game.core.system.CharacterMovement.position:type_name -> game.core.system.Vector2
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_modules_game_core_system_player_movement_proto_init() }
func file_modules_game_core_system_player_movement_proto_init() {
	if File_modules_game_core_system_player_movement_proto != nil {
		return
	}
	file_modules_game_core_system_vector_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_game_core_system_player_movement_proto_rawDesc), len(file_modules_game_core_system_player_movement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modules_game_core_system_player_movement_proto_goTypes,
		DependencyIndexes: file_modules_game_core_system_player_movement_proto_depIdxs,
		MessageInfos:      file_modules_game_core_system_player_movement_proto_msgTypes,
	}.Build()
	File_modules_game_core_system_player_movement_proto = out.File
	file_modules_game_core_system_player_movement_proto_goTypes = nil
	file_modules_game_core_system_player_movement_proto_depIdxs = nil
}
