// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: modules/game/core/system/player_progression.proto

package system

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerProgressionBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          int64                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Players       []*PlayerProgression   `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerProgressionBatch) Reset() {
	*x = PlayerProgressionBatch{}
	mi := &file_modules_game_core_system_player_progression_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerProgressionBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProgressionBatch) ProtoMessage() {}

func (x *PlayerProgressionBatch) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_system_player_progression_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProgressionBatch.ProtoReflect.Descriptor instead.
func (*PlayerProgressionBatch) Descriptor() ([]byte, []int) {
	return file_modules_game_core_system_player_progression_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerProgressionBatch) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *PlayerProgressionBatch) GetPlayers() []*PlayerProgression {
	if x != nil {
		return x.Players
	}
	return nil
}

type PlayerProgression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Experience    uint64                 `protobuf:"varint,4,opt,name=experience,proto3" json:"experience,omitempty"`
	MaxExperience uint64                 `protobuf:"varint,5,opt,name=max_experience,json=maxExperience,proto3" json:"max_experience,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerProgression) Reset() {
	*x = PlayerProgression{}
	mi := &file_modules_game_core_system_player_progression_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerProgression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProgression) ProtoMessage() {}

func (x *PlayerProgression) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_system_player_progression_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProgression.ProtoReflect.Descriptor instead.
func (*PlayerProgression) Descriptor() ([]byte, []int) {
	return file_modules_game_core_system_player_progression_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerProgression) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlayerProgression) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PlayerProgression) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerProgression) GetExperience() uint64 {
	if x != nil {
		return x.Experience
	}
	return 0
}

func (x *PlayerProgression) GetMaxExperience() uint64 {
	if x != nil {
		return x.MaxExperience
	}
	return 0
}

var File_modules_game_core_system_player_progression_proto protoreflect.FileDescriptor

const file_modules_game_core_system_player_progression_proto_rawDesc = "" +
	"\n" +
	"1modules/game/core/system/player_progression.proto\x12\x10game.core.system\"k\n" +
	"\x16PlayerProgressionBatch\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x03R\x04tick\x12=\n" +
	"\aplayers\x18\x02 \x03(\v2#.game.core.system.PlayerProgressionR\aplayers\"\xa8\x01\n" +
	"\x11PlayerProgression\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x1e\n" +
	"\n" +
	"experience\x18\x04 \x01(\x04R\n" +
	"experience\x12%\n" +
	"\x0emax_experience\x18\x05 \x01(\x04R\rmaxExperienceB3Z1squad-survival-be/modules/game/core/system;systemb\x06proto3"

var (
	file_modules_game_core_system_player_progression_proto_rawDescOnce sync.Once
	file_modules_game_core_system_player_progression_proto_rawDescData []byte
)

func file_modules_game_core_system_player_progression_proto_rawDescGZIP() []byte {
	file_modules_game_core_system_player_progression_proto_rawDescOnce.Do(func() {
		file_modules_game_core_system_player_progression_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_game_core_system_player_progression_proto_rawDesc), len(file_modules_game_core_system_player_progression_proto_rawDesc)))
	})
	return file_modules_game_core_system_player_progression_proto_rawDescData
}

var file_modules_game_core_system_player_progression_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_modules_game_core_system_player_progression_proto_goTypes = []any{
	(*PlayerProgressionBatch)(nil), // 0: game.core.system.PlayerProgressionBatch
	(*PlayerProgression)(nil),      // 1: game.core.system.PlayerProgression
}
var file_modules_game_core_system_player_progression_proto_depIdxs = []int32{
	1, // 0: game.core.system.PlayerProgressionBatch.players:type_name -> game.core.system.PlayerProgression
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_modules_game_core_system_player_progression_proto_init() }
func file_modules_game_core_system_player_progression_proto_init() {
	if File_modules_game_core_system_player_progression_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_game_core_system_player_progression_proto_rawDesc), len(file_modules_game_core_system_player_progression_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modules_game_core_system_player_progression_proto_goTypes,
		DependencyIndexes: file_modules_game_core_system_player_progression_proto_depIdxs,
		MessageInfos:      file_modules_game_core_system_player_progression_proto_msgTypes,
	}.Build()
	File_modules_game_core_system_player_progression_proto = out.File
	file_modules_game_core_system_player_progression_proto_goTypes = nil
	file_modules_game_core_system_player_progression_proto_depIdxs = nil
}
