// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: modules/game/core/system/projectile_movement.proto

package system

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectileMovementSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          int64                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Projectiles   []*ProjectileMovement  `protobuf:"bytes,2,rep,name=projectiles,proto3" json:"projectiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectileMovementSnapshot) Reset() {
	*x = ProjectileMovementSnapshot{}
	mi := &file_modules_game_core_system_projectile_movement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectileMovementSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectileMovementSnapshot) ProtoMessage() {}

func (x *ProjectileMovementSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_system_projectile_movement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectileMovementSnapshot.ProtoReflect.Descriptor instead.
func (*ProjectileMovementSnapshot) Descriptor() ([]byte, []int) {
	return file_modules_game_core_system_projectile_movement_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectileMovementSnapshot) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *ProjectileMovementSnapshot) GetProjectiles() []*ProjectileMovement {
	if x != nil {
		return x.Projectiles
	}
	return nil
}

type ProjectileMovement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectileId  string                 `protobuf:"bytes,1,opt,name=projectile_id,json=projectileId,proto3" json:"projectile_id,omitempty"`
	Position      *Vector2               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectileMovement) Reset() {
	*x = ProjectileMovement{}
	mi := &file_modules_game_core_system_projectile_movement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectileMovement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectileMovement) ProtoMessage() {}

func (x *ProjectileMovement) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_system_projectile_movement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectileMovement.ProtoReflect.Descriptor instead.
func (*ProjectileMovement) Descriptor() ([]byte, []int) {
	return file_modules_game_core_system_projectile_movement_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectileMovement) GetProjectileId() string {
	if x != nil {
		return x.ProjectileId
	}
	return ""
}

func (x *ProjectileMovement) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

var File_modules_game_core_system_projectile_movement_proto protoreflect.FileDescriptor

const file_modules_game_core_system_projectile_movement_proto_rawDesc = "" +
	"\n" +
	"2modules/game/core/system/projectile_movement.proto\x12\x10game.core.system\x1a%modules/game/core/system/vector.proto\"x\n" +
	"\x1aProjectileMovementSnapshot\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x03R\x04tick\x12F\n" +
	"\vprojectiles\x18\x02 \x03(\v2$.game.core.system.ProjectileMovementR\vprojectiles\"p\n" +
	"\x12ProjectileMovement\x12#\n" +
	"\rprojectile_id\x18\x01 \x01(\tR\fprojectileId\x125\n" +
	"\bposition\x18\x02 \x01(\v2\x19.game.core.system.Vector2R\bpositionB3Z1squad-survival-be/modules/game/core/system;systemb\x06proto3"

var (
	file_modules_game_core_system_projectile_movement_proto_rawDescOnce sync.Once
	file_modules_game_core_system_projectile_movement_proto_rawDescData []byte
)

func file_modules_game_core_system_projectile_movement_proto_rawDescGZIP() []byte {
	file_modules_game_core_system_projectile_movement_proto_rawDescOnce.Do(func() {
		file_modules_game_core_system_projectile_movement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_game_core_system_projectile_movement_proto_rawDesc), len(file_modules_game_core_system_projectile_movement_proto_rawDesc)))
	})
	return file_modules_game_core_system_projectile_movement_proto_rawDescData
}

var file_modules_game_core_system_projectile_movement_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_modules_game_core_system_projectile_movement_proto_goTypes = []any{
	(*ProjectileMovementSnapshot)(nil), // 0: game.core.system.ProjectileMovementSnapshot
	(*ProjectileMovement)(nil),         // 1: game.core.system.ProjectileMovement
	(*Vector2)(nil),                    // 2: game.core.system.Vector2
}
var file_modules_game_core_system_projectile_movement_proto_depIdxs = []int32{
	1, // 0: game.core.system.ProjectileMovementSnapshot.projectiles:type_name -> game.core.system.ProjectileMovement
	2, // 1: game.core.system.ProjectileMovement.position:type_name -> game.core.system.Vector2
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_modules_game_core_system_projectile_movement_proto_init() }
func file_modules_game_core_system_projectile_movement_proto_init() {
	if File_modules_game_core_system_projectile_movement_proto != nil {
		return
	}
	file_modules_game_core_system_vector_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_game_core_system_projectile_movement_proto_rawDesc), len(file_modules_game_core_system_projectile_movement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modules_game_core_system_projectile_movement_proto_goTypes,
		DependencyIndexes: file_modules_game_core_system_projectile_movement_proto_depIdxs,
		MessageInfos:      file_modules_game_core_system_projectile_movement_proto_msgTypes,
	}.Build()
	File_modules_game_core_system_projectile_movement_proto = out.File
	file_modules_game_core_system_projectile_movement_proto_goTypes = nil
	file_modules_game_core_system_projectile_movement_proto_depIdxs = nil
}
