// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: modules/game/core/system/roster.proto

package system

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerRosterBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          int64                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Players       []*PlayerRoster        `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerRosterBatch) Reset() {
	*x = PlayerRosterBatch{}
	mi := &file_modules_game_core_system_roster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRosterBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRosterBatch) ProtoMessage() {}

func (x *PlayerRosterBatch) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_system_roster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRosterBatch.ProtoReflect.Descriptor instead.
func (*PlayerRosterBatch) Descriptor() ([]byte, []int) {
	return file_modules_game_core_system_roster_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerRosterBatch) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *PlayerRosterBatch) GetPlayers() []*PlayerRoster {
	if x != nil {
		return x.Players
	}
	return nil
}

type PlayerRoster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	RosterVersion uint64                 `protobuf:"varint,4,opt,name=roster_version,json=rosterVersion,proto3" json:"roster_version,omitempty"`
	Characters    []*CharacterRoster     `protobuf:"bytes,5,rep,name=characters,proto3" json:"characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerRoster) Reset() {
	*x = PlayerRoster{}
	mi := &file_modules_game_core_system_roster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRoster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRoster) ProtoMessage() {}

func (x *PlayerRoster) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_system_roster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRoster.ProtoReflect.Descriptor instead.
func (*PlayerRoster) Descriptor() ([]byte, []int) {
	return file_modules_game_core_system_roster_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerRoster) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlayerRoster) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PlayerRoster) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PlayerRoster) GetRosterVersion() uint64 {
	if x != nil {
		return x.RosterVersion
	}
	return 0
}

func (x *PlayerRoster) GetCharacters() []*CharacterRoster {
	if x != nil {
		return x.Characters
	}
	return nil
}

type CharacterRoster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Health        float64                `protobuf:"fixed64,2,opt,name=health,proto3" json:"health,omitempty"`
	MaxHealth     float64                `protobuf:"fixed64,3,opt,name=max_health,json=maxHealth,proto3" json:"max_health,omitempty"`
	Damage        float64                `protobuf:"fixed64,4,opt,name=damage,proto3" json:"damage,omitempty"`
	MoveSpeed     float64                `protobuf:"fixed64,5,opt,name=move_speed,json=moveSpeed,proto3" json:"move_speed,omitempty"`
	AttackSpeed   float64                `protobuf:"fixed64,6,opt,name=attack_speed,json=attackSpeed,proto3" json:"attack_speed,omitempty"`
	AttackRange   float64                `protobuf:"fixed64,7,opt,name=attack_range,json=attackRange,proto3" json:"attack_range,omitempty"`
	RegenRate     float64                `protobuf:"fixed64,8,opt,name=regen_rate,json=regenRate,proto3" json:"regen_rate,omitempty"`
	DamageRatio   float64                `protobuf:"fixed64,9,opt,name=damage_ratio,json=damageRatio,proto3" json:"damage_ratio,omitempty"`
	WeaponType    string                 `protobuf:"bytes,10,opt,name=weapon_type,json=weaponType,proto3" json:"weapon_type,omitempty"`
	RangeClass    string                 `protobuf:"bytes,11,opt,name=range_class,json=rangeClass,proto3" json:"range_class,omitempty"`
	WeaponName    string                 `protobuf:"bytes,12,opt,name=weapon_name,json=weaponName,proto3" json:"weapon_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterRoster) Reset() {
	*x = CharacterRoster{}
	mi := &file_modules_game_core_system_roster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterRoster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterRoster) ProtoMessage() {}

func (x *CharacterRoster) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_system_roster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterRoster.ProtoReflect.Descriptor instead.
func (*CharacterRoster) Descriptor() ([]byte, []int) {
	return file_modules_game_core_system_roster_proto_rawDescGZIP(), []int{2}
}

func (x *CharacterRoster) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *CharacterRoster) GetHealth() float64 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *CharacterRoster) GetMaxHealth() float64 {
	if x != nil {
		return x.MaxHealth
	}
	return 0
}

func (x *CharacterRoster) GetDamage() float64 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *CharacterRoster) GetMoveSpeed() float64 {
	if x != nil {
		return x.MoveSpeed
	}
	return 0
}

func (x *CharacterRoster) GetAttackSpeed() float64 {
	if x != nil {
		return x.AttackSpeed
	}
	return 0
}

func (x *CharacterRoster) GetAttackRange() float64 {
	if x != nil {
		return x.AttackRange
	}
	return 0
}

func (x *CharacterRoster) GetRegenRate() float64 {
	if x != nil {
		return x.RegenRate
	}
	return 0
}

func (x *CharacterRoster) GetDamageRatio() float64 {
	if x != nil {
		return x.DamageRatio
	}
	return 0
}

func (x *CharacterRoster) GetWeaponType() string {
	if x != nil {
		return x.WeaponType
	}
	return ""
}

func (x *CharacterRoster) GetRangeClass() string {
	if x != nil {
		return x.RangeClass
	}
	return ""
}

func (x *CharacterRoster) GetWeaponName() string {
	if x != nil {
		return x.WeaponName
	}
	return ""
}

var File_modules_game_core_system_roster_proto protoreflect.FileDescriptor

const file_modules_game_core_system_roster_proto_rawDesc = "" +
	"\n" +
	"%modules/game/core/system/roster.proto\x12\x10game.core.system\"a\n" +
	"\x11PlayerRosterBatch\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x03R\x04tick\x128\n" +
	"\aplayers\x18\x02 \x03(\v2\x1e.game.core.system.PlayerRosterR\aplayers\"\xd3\x01\n" +
	"\fPlayerRoster\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12%\n" +
	"\x0eroster_version\x18\x04 \x01(\x04R\rrosterVersion\x12A\n" +
	"\n" +
	"characters\x18\x05 \x03(\v2!.game.core.system.CharacterRosterR\n" +
	"characters\"\x8d\x03\n" +
	"\x0fCharacterRoster\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12\x16\n" +
	"\x06health\x18\x02 \x01(\x01R\x06health\x12\x1d\n" +
	"\n" +
	"max_health\x18\x03 \x01(\x01R\tmaxHealth\x12\x16\n" +
	"\x06damage\x18\x04 \x01(\x01R\x06damage\x12\x1d\n" +
	"\n" +
	"move_speed\x18\x05 \x01(\x01R\tmoveSpeed\x12!\n" +
	"\fattack_speed\x18\x06 \x01(\x01R\vattackSpeed\x12!\n" +
	"\fattack_range\x18\a \x01(\x01R\vattackRange\x12\x1d\n" +
	"\n" +
	"regen_rate\x18\b \x01(\x01R\tregenRate\x12!\n" +
	"\fdamage_ratio\x18\t \x01(\x01R\vdamageRatio\x12\x1f\n" +
	"\vweapon_type\x18\n" +
	" \x01(\tR\n" +
	"weaponType\x12\x1f\n" +
	"\vrange_class\x18\v \x01(\tR\n" +
	"rangeClass\x12\x1f\n" +
	"\vweapon_name\x18\f \x01(\tR\n" +
	"weaponNameB3Z1squad-survival-be/modules/game/core/system;systemb\x06proto3"

var (
	file_modules_game_core_system_roster_proto_rawDescOnce sync.Once
	file_modules_game_core_system_roster_proto_rawDescData []byte
)

func file_modules_game_core_system_roster_proto_rawDescGZIP() []byte {
	file_modules_game_core_system_roster_proto_rawDescOnce.Do(func() {
		file_modules_game_core_system_roster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_game_core_system_roster_proto_rawDesc), len(file_modules_game_core_system_roster_proto_rawDesc)))
	})
	return file_modules_game_core_system_roster_proto_rawDescData
}

var file_modules_game_core_system_roster_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_modules_game_core_system_roster_proto_goTypes = []any{
	(*PlayerRosterBatch)(nil), // 0: game.core.system.PlayerRosterBatch
	(*PlayerRoster)(nil),      // 1: game.core.system.PlayerRoster
	(*CharacterRoster)(nil),   // 2: game.core.system.CharacterRoster
}
var file_modules_game_core_system_roster_proto_depIdxs = []int32{
	1, // 0: game.core.system.PlayerRosterBatch.players:type_name -> game.core.system.PlayerRoster
	2, // 1: game.core.system.PlayerRoster.characters:type_name -> game.core.system.CharacterRoster
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_modules_game_core_system_roster_proto_init() }
func file_modules_game_core_system_roster_proto_init() {
	if File_modules_game_core_system_roster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_game_core_system_roster_proto_rawDesc), len(file_modules_game_core_system_roster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modules_game_core_system_roster_proto_goTypes,
		DependencyIndexes: file_modules_game_core_system_roster_proto_depIdxs,
		MessageInfos:      file_modules_game_core_system_roster_proto_msgTypes,
	}.Build()
	File_modules_game_core_system_roster_proto = out.File
	file_modules_game_core_system_roster_proto_goTypes = nil
	file_modules_game_core_system_roster_proto_depIdxs = nil
}
