// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: modules/game/core/system/skill_state.proto

package system

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SkillStateBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          int64                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	States        []*SkillState          `protobuf:"bytes,2,rep,name=states,proto3" json:"states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillStateBatch) Reset() {
	*x = SkillStateBatch{}
	mi := &file_modules_game_core_system_skill_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillStateBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillStateBatch) ProtoMessage() {}

func (x *SkillStateBatch) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_system_skill_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillStateBatch.ProtoReflect.Descriptor instead.
func (*SkillStateBatch) Descriptor() ([]byte, []int) {
	return file_modules_game_core_system_skill_state_proto_rawDescGZIP(), []int{0}
}

func (x *SkillStateBatch) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *SkillStateBatch) GetStates() []*SkillState {
	if x != nil {
		return x.States
	}
	return nil
}

type SkillState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CharacterId   string                 `protobuf:"bytes,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Cooldowns     []*SkillCooldown       `protobuf:"bytes,4,rep,name=cooldowns,proto3" json:"cooldowns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillState) Reset() {
	*x = SkillState{}
	mi := &file_modules_game_core_system_skill_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillState) ProtoMessage() {}

func (x *SkillState) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_system_skill_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillState.ProtoReflect.Descriptor instead.
func (*SkillState) Descriptor() ([]byte, []int) {
	return file_modules_game_core_system_skill_state_proto_rawDescGZIP(), []int{1}
}

func (x *SkillState) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SkillState) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *SkillState) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SkillState) GetCooldowns() []*SkillCooldown {
	if x != nil {
		return x.Cooldowns
	}
	return nil
}

var File_modules_game_core_system_skill_state_proto protoreflect.FileDescriptor

const file_modules_game_core_system_skill_state_proto_rawDesc = "" +
	"\n" +
	"*modules/game/core/system/skill_state.proto\x12\x10game.core.system\x1a%modules/game/core/system/roster.proto\"[\n" +
	"\x0fSkillStateBatch\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x03R\x04tick\x124\n" +
	"\x06states\x18\x02 \x03(\v2\x1c.game.core.system.SkillStateR\x06states\"\xa1\x01\n" +
	"\n" +
	"SkillState\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fcharacter_id\x18\x02 \x01(\tR\vcharacterId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12=\n" +
	"\tcooldowns\x18\x04 \x03(\v2\x1f.game.core.system.SkillCooldownR\tcooldownsB3Z1squad-survival-be/modules/game/core/system;systemb\x06proto3"

var (
	file_modules_game_core_system_skill_state_proto_rawDescOnce sync.Once
	file_modules_game_core_system_skill_state_proto_rawDescData []byte
)

func file_modules_game_core_system_skill_state_proto_rawDescGZIP() []byte {
	file_modules_game_core_system_skill_state_proto_rawDescOnce.Do(func() {
		file_modules_game_core_system_skill_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_game_core_system_skill_state_proto_rawDesc), len(file_modules_game_core_system_skill_state_proto_rawDesc)))
	})
	return file_modules_game_core_system_skill_state_proto_rawDescData
}

var file_modules_game_core_system_skill_state_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_modules_game_core_system_skill_state_proto_goTypes = []any{
	(*SkillStateBatch)(nil), // 0: game.core.system.SkillStateBatch
	(*SkillState)(nil),      // 1: game.core.system.SkillState
	(*SkillCooldown)(nil),   // 2: game.core.system.SkillCooldown
}
var file_modules_game_core_system_skill_state_proto_depIdxs = []int32{
	1, // 0: game.core.system.SkillStateBatch.states:type_name -> game.core.system.SkillState
	2, // 1: game.core.system.SkillState.cooldowns:type_name -> game.core.system.SkillCooldown
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_modules_game_core_system_skill_state_proto_init() }
func file_modules_game_core_system_skill_state_proto_init() {
	if File_modules_game_core_system_skill_state_proto != nil {
		return
	}
	file_modules_game_core_system_roster_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_game_core_system_skill_state_proto_rawDesc), len(file_modules_game_core_system_skill_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modules_game_core_system_skill_state_proto_goTypes,
		DependencyIndexes: file_modules_game_core_system_skill_state_proto_depIdxs,
		MessageInfos:      file_modules_game_core_system_skill_state_proto_msgTypes,
	}.Build()
	File_modules_game_core_system_skill_state_proto = out.File
	file_modules_game_core_system_skill_state_proto_goTypes = nil
	file_modules_game_core_system_skill_state_proto_depIdxs = nil
}
