// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: modules/game/core/system/skin.proto

package system

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CharacterSkin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HairId        int32                  `protobuf:"varint,1,opt,name=hair_id,json=hairId,proto3" json:"hair_id,omitempty"`
	BeardId       int32                  `protobuf:"varint,2,opt,name=beard_id,json=beardId,proto3" json:"beard_id,omitempty"`
	ChestId       int32                  `protobuf:"varint,3,opt,name=chest_id,json=chestId,proto3" json:"chest_id,omitempty"`
	EyeId         int32                  `protobuf:"varint,4,opt,name=eye_id,json=eyeId,proto3" json:"eye_id,omitempty"`
	HelmetId      int32                  `protobuf:"varint,5,opt,name=helmet_id,json=helmetId,proto3" json:"helmet_id,omitempty"`
	WeaponId      int32                  `protobuf:"varint,6,opt,name=weapon_id,json=weaponId,proto3" json:"weapon_id,omitempty"`
	ProjectileId  int32                  `protobuf:"varint,7,opt,name=projectile_id,json=projectileId,proto3" json:"projectile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterSkin) Reset() {
	*x = CharacterSkin{}
	mi := &file_modules_game_core_system_skin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterSkin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterSkin) ProtoMessage() {}

func (x *CharacterSkin) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_system_skin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterSkin.ProtoReflect.Descriptor instead.
func (*CharacterSkin) Descriptor() ([]byte, []int) {
	return file_modules_game_core_system_skin_proto_rawDescGZIP(), []int{0}
}

func (x *CharacterSkin) GetHairId() int32 {
	if x != nil {
		return x.HairId
	}
	return 0
}

func (x *CharacterSkin) GetBeardId() int32 {
	if x != nil {
		return x.BeardId
	}
	return 0
}

func (x *CharacterSkin) GetChestId() int32 {
	if x != nil {
		return x.ChestId
	}
	return 0
}

func (x *CharacterSkin) GetEyeId() int32 {
	if x != nil {
		return x.EyeId
	}
	return 0
}

func (x *CharacterSkin) GetHelmetId() int32 {
	if x != nil {
		return x.HelmetId
	}
	return 0
}

func (x *CharacterSkin) GetWeaponId() int32 {
	if x != nil {
		return x.WeaponId
	}
	return 0
}

func (x *CharacterSkin) GetProjectileId() int32 {
	if x != nil {
		return x.ProjectileId
	}
	return 0
}

var File_modules_game_core_system_skin_proto protoreflect.FileDescriptor

const file_modules_game_core_system_skin_proto_rawDesc = "" +
	"\n" +
	"#modules/game/core/system/skin.proto\x12\x10game.core.system\"\xd4\x01\n" +
	"\rCharacterSkin\x12\x17\n" +
	"\ahair_id\x18\x01 \x01(\x05R\x06hairId\x12\x19\n" +
	"\bbeard_id\x18\x02 \x01(\x05R\abeardId\x12\x19\n" +
	"\bchest_id\x18\x03 \x01(\x05R\achestId\x12\x15\n" +
	"\x06eye_id\x18\x04 \x01(\x05R\x05eyeId\x12\x1b\n" +
	"\thelmet_id\x18\x05 \x01(\x05R\bhelmetId\x12\x1b\n" +
	"\tweapon_id\x18\x06 \x01(\x05R\bweaponId\x12#\n" +
	"\rprojectile_id\x18\a \x01(\x05R\fprojectileIdB3Z1squad-survival-be/modules/game/core/system;systemb\x06proto3"

var (
	file_modules_game_core_system_skin_proto_rawDescOnce sync.Once
	file_modules_game_core_system_skin_proto_rawDescData []byte
)

func file_modules_game_core_system_skin_proto_rawDescGZIP() []byte {
	file_modules_game_core_system_skin_proto_rawDescOnce.Do(func() {
		file_modules_game_core_system_skin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_game_core_system_skin_proto_rawDesc), len(file_modules_game_core_system_skin_proto_rawDesc)))
	})
	return file_modules_game_core_system_skin_proto_rawDescData
}

var file_modules_game_core_system_skin_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_modules_game_core_system_skin_proto_goTypes = []any{
	(*CharacterSkin)(nil), // 0: game.core.system.CharacterSkin
}
var file_modules_game_core_system_skin_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_modules_game_core_system_skin_proto_init() }
func file_modules_game_core_system_skin_proto_init() {
	if File_modules_game_core_system_skin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_game_core_system_skin_proto_rawDesc), len(file_modules_game_core_system_skin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modules_game_core_system_skin_proto_goTypes,
		DependencyIndexes: file_modules_game_core_system_skin_proto_depIdxs,
		MessageInfos:      file_modules_game_core_system_skin_proto_msgTypes,
	}.Build()
	File_modules_game_core_system_skin_proto = out.File
	file_modules_game_core_system_skin_proto_goTypes = nil
	file_modules_game_core_system_skin_proto_depIdxs = nil
}
